Renamed ADDetectorTest2 so that it ends in Test and is run by Jenkins
This test currently fails on my local machine due to:

java.lang.NoClassDefFoundError: Could not initialize class gda.data.nexus.GdaNexusFile

Hopefully the library is set up better on Jenkins